version: '3'
services:
  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example-dev
    ports:
      - 5433:5432
